'''Project Euler 45 Triangle, pentagonal, and hexagonal
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.
Find the next triangle number that is also pentagonal and hexagonal.
'''
import Helpers

class pe45:
    #just iterate through tri numbers and compare if penta
    def __init__(self):
        self._triNums = []
        self._pentNums = []
        self._hexNums = []

    def triAndPenAndHexgen(self):
        '''generator function - use .next() to get next value'''
        for tri in self._triNums:
            if (tri in self._pentNums) and (tri in self._hexNums):
                yield tri

    def main(self):
        #hex is a subset of tri
        self._triNums = Helpers.getTriangleNumbers(56700)
        self._pentNums = Helpers.getPentagonalNumbers(56000)
        self._hexNums = Helpers.getHexagonalNumbers(56000)
        results = self.triAndPenAndHexgen()
        for i in range(3):
            print results.next()
        
if __name__ == "__main__":
    c = pe45()
    c.main()